### ISSUE TITLE
public resources aren't loaded when deployed on different than root path

### ISSUE THREAD

**Issue by jacobStankaitis** [sudarakas/realproperty#16]
Css, js and pages are redirected to root instead of working directory

**Comment by sudarakas** [comment]
> Css, js and pages are redirected to root instead of the working directory

have you tried changing the index.php? if you move the public folder away from the default folder structure you should also change the index.php inside in public folder

**Comment by sudarakas** [comment]
due to inactivity, I'm going close to this issue
