### ISSUE TITLE
Migration to Laravel 8

### ISSUE THREAD

**Issue by marll** [sudarakas/realproperty#21]
Hi,
is possible update to laravel 8 or  is more easy doing a fresh install and just migrate your code over.
Many thanks

**Comment by sudarakas** [comment]
do a fresh install and migrate

**Comment by danielkaranja0** [comment]
Hi, am new to laravel could you kindly guide on the way to install it

**Comment by sudarakas** [comment]
> Hi, am new to laravel could you kindly guide on the way to install it

Hi, 

clone the repo
then open the terminal and type `composer update` hit enter
then type `php artisan key:generate`
setup the .env file and you're doe

**Comment by ugintl** [comment]
@marll How did you generate the data? can you share the mysql file?

**Comment by marll** [comment]
@ugintl  I haven't generated it anymore, sorry

**Comment by sudarakas** [comment]
> @marll How did you generate the data? can you share the mysql file?

php artisan migrate
